"""
Skill de generación de código.
Provee utilidades para aplicar estándares, generar headers y detectar el stack.
Sin dependencias externas — solo stdlib.
"""
from __future__ import annotations

import json
import re
from pathlib import Path


class CodegenSkill:
    """Utilidades de codegen para usar desde el orquestador o los agentes."""

    # Extensiones → (apertura, prefijo_línea, cierre)
    _HEADER_STYLES: dict[str, tuple[str, str, str]] = {
        ".ts":   ("/**", " * ", " */"),
        ".tsx":  ("/**", " * ", " */"),
        ".js":   ("/**", " * ", " */"),
        ".jsx":  ("/**", " * ", " */"),
        ".java": ("/**", " * ", " */"),
        ".py":   ('"""', "", '"""'),
        ".go":   ("//", "// ", "//"),
        ".rs":   ("//!", "//! ", "//!"),
        ".sh":   ("#", "# ", "#"),
        ".yaml": ("#", "# ", "#"),
        ".yml":  ("#", "# ", "#"),
        ".toml": ("#", "# ", "#"),
        ".css":  ("/*", " * ", " */"),
        ".scss": ("/*", " * ", " */"),
        ".sql":  ("--", "-- ", "--"),
    }

    def apply_standards(
        self,
        code: str,
        file_path: str,
        namespace_standards: str,
    ) -> str:
        """
        Analiza el código contra los estándares del namespace y retorna
        un reporte de sugerencias. No modifica el archivo.
        """
        ext = Path(file_path).suffix.lower()
        issues: list[str] = []
        lines = code.splitlines()

        # Líneas muy largas
        long_lines = [
            f"  Línea {i+1}: {len(line)} chars"
            for i, line in enumerate(lines)
            if len(line) > 200
        ]
        if long_lines:
            issues.append("Líneas muy largas (>200 chars):\n" + "\n".join(long_lines[:5]))

        if ext in (".ts", ".tsx", ".js", ".jsx"):
            if "console.log" in code:
                issues.append("Contiene console.log — considera reemplazar con logger estructurado.")
            if ext in (".ts", ".tsx"):
                any_count = len(re.findall(r"\bany\b", code))
                if any_count > 3:
                    issues.append(f"Uso de 'any' detectado {any_count} veces — define tipos explícitos.")
            todos = [f"  Línea {i+1}" for i, l in enumerate(lines) if "TODO" in l or "FIXME" in l]
            if todos:
                issues.append("TODOs/FIXMEs pendientes:\n" + "\n".join(todos[:5]))

        if ext == ".py":
            if "print(" in code:
                issues.append("Contiene print() — considera usar logging.")
            if re.search(r"except\s*:", code):
                issues.append("Cláusula 'except:' sin tipo — captura excepciones concretas.")

        if not issues:
            return f"✓ {file_path}: sin observaciones de estándares."

        report = f"Revisión de estándares para {file_path}:\n\n"
        for i, issue in enumerate(issues, 1):
            report += f"{i}. {issue}\n\n"
        return report.strip()

    def generate_file_header(
        self,
        file_path: str,
        description: str,
        author: str = "agent-workspace",
    ) -> str:
        """
        Genera el bloque de comentario de cabecera apropiado para el archivo
        según su extensión.
        """
        ext = Path(file_path).suffix.lower()
        style = self._HEADER_STYLES.get(ext)

        if not style:
            return f"# {description}\n# Generated by {author}\n"

        open_mark, line_prefix, close_mark = style

        if ext == ".py":
            return f'{open_mark}\n{description}\nGenerated by {author}\n{close_mark}\n'
        elif open_mark == close_mark:
            # Estilo línea simple (go, sh, yaml, etc.)
            return f"{line_prefix}{description}\n{line_prefix}Generated by {author}\n"
        else:
            return (
                f"{open_mark}\n"
                f"{line_prefix}{description}\n"
                f"{line_prefix}@generated {author}\n"
                f"{close_mark}\n"
            )

    def detect_stack(self, project_root: str | Path) -> list[str]:
        """
        Lee package.json / pyproject.toml / requirements.txt y retorna
        el stack detectado como lista de strings.
        """
        root = Path(project_root)
        stack: list[str] = []

        pkg_json = root / "package.json"
        if pkg_json.exists():
            try:
                data = json.loads(pkg_json.read_text(encoding="utf-8"))
                deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
                _known = {
                    "next":           "Next.js",
                    "react":          "React",
                    "vue":            "Vue.js",
                    "@nestjs/core":   "NestJS",
                    "express":        "Express",
                    "fastify":        "Fastify",
                    "typescript":     "TypeScript",
                    "tailwindcss":    "TailwindCSS",
                    "prisma":         "Prisma",
                    "@prisma/client": "Prisma",
                    "jest":           "Jest",
                    "vitest":         "Vitest",
                    "playwright":     "Playwright",
                    "vite":           "Vite",
                }
                for key, label in _known.items():
                    if key in deps and label not in stack:
                        stack.append(label)
                if not any(x in stack for x in ("TypeScript", "JavaScript")):
                    stack.append("TypeScript" if "typescript" in deps else "JavaScript")
            except (json.JSONDecodeError, OSError):
                pass

        pyproject = root / "pyproject.toml"
        if pyproject.exists():
            try:
                text = pyproject.read_text(encoding="utf-8").lower()
                stack.append("Python")
                for key, label in {
                    "fastapi": "FastAPI", "django": "Django", "flask": "Flask",
                    "sqlalchemy": "SQLAlchemy", "pytest": "pytest", "crewai": "CrewAI",
                }.items():
                    if key in text:
                        stack.append(label)
            except OSError:
                pass

        req_txt = root / "requirements.txt"
        if req_txt.exists() and "Python" not in stack:
            try:
                text = req_txt.read_text(encoding="utf-8").lower()
                stack.append("Python")
                for key, label in {"fastapi": "FastAPI", "django": "Django", "flask": "Flask"}.items():
                    if key in text:
                        stack.append(label)
            except OSError:
                pass

        if (root / "Dockerfile").exists() or (root / "docker-compose.yml").exists():
            stack.append("Docker")

        return stack or ["(stack no detectado)"]


# Instancia por defecto
codegen = CodegenSkill()


def apply_standards(code: str, stack: list[str]) -> str:
    """Compatibilidad con la API de v1."""
    return code
